//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Session = new HashSet<Session>();
            this.Country = new HashSet<Country>();
            this.Genre = new HashSet<Genre>();
        }
    
        [Required]
        public int Film_ID { get; set; }
        [Required]
        [DisplayName("Название:")]
        public string name { get; set; }
        [Required]
        [DisplayName("Год:")]
        public int year { get; set; }
        [Required]
        [DisplayName("Режиссёр:")]
        public string director { get; set; }
        [Required]
        [DisplayName("Актёрский состав:")]
        public string cast { get; set; }
        [Required]
        [DisplayName("Длительность:")]
        public System.TimeSpan duration { get; set; }
        public System.DateTime release_date_from { get; set; }
        public System.DateTime release_date_till { get; set; }
        [Required]
        [DisplayName("Описание:")]
        public string description { get; set; }
        [Required]
        [DisplayName("Рейтинг:")]
        public Nullable<float> rating { get; set; }
        public string rating_url { get; set; }
        [Required]
        [DisplayName("Цена: от")]
        public int price { get; set; }
        public string img_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genre> Genre { get; set; }
    }
}
